name: Publish Packages

on:
  push:
    tags:
       - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build hdijupyterutils dist
        run: |
          cd hdijupyterutils
          python setup.py sdist
          cd ..

      - name: Build autovizwidget dist
        run: |
          cd autovizwidget
          python setup.py sdist
          cd ..

      - name: Build sparkmagic dist
        run: |
          cd sparkmagic
          python setup.py sdist
          cd ..

      - name: Publish distribution to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            hdijupyterutils/dist/*
            autovizwidget/dist/*
            sparkmagic/dist/*
